### PR TITLE
closed #8843: Fixes DrawNode::drawPoint crash and uses VAO if it's available when draw points.

### LINKED ISSUE #8843: Crash DrawNode::drawPoint()
Try the following code in cpp-tests, DrawPrimitivesTest.cpp in `DrawNodeTest()`

```
Vec2 positions[100];
for (int i = 0; i < 100; i++) {
    draw->drawPoint(Vec2(i, 5), 1, Color4F(CCRANDOM_0_1(), CCRANDOM_0_1(), CCRANDOM_0_1(), 1));
}
```

It causes a crash.
Tested as win32 app in Visual Studio 2013.

### PR DESCRIPTION
**Pull request by dumganhar**
Fixed issue #8843

### CODE REVIEW

File: cocos/2d/CCDrawNode.cpp [hunk 1]
```diff
@@ -415,6 +425,8 @@ void DrawNode::onDrawGLPoint(const Mat4 &transform, uint32_t flags)
 
 void DrawNode::drawPoint(const Vec2& position, const float pointSize, const Color4F &color)
 {
+    ensureCapacityGLPoint(1);
```
Comment (dumganhar) [inline cocos/2d/CCDrawNode.cpp:428]: This line resolves the crash issue. :)

**Comment by minggo** [comment]
@huangshiwu 
Please help to review it.

**Comment by minggo** [comment]
[ci rebuild]
