### PR TITLE
fixed #16477: [android, audio] Deadlock if preload the same file more than 3 times in preload callback.

### LINKED ISSUE #16477: Deadlock if preload the same file more than 3 times in preload callback
- cocos2d-x version:3.13
- devices test on: Android
- developing environments
  - NDK version: r10e

Steps to Reproduce:

``` c++
        AudioEngine::preload("audio/SoundEffectsFX009/FX082.mp3", [i](bool isSucceed){
            log("111: %d preload %s", i, isSucceed ? "succeed" : "failed");
            AudioEngine::preload("audio/SoundEffectsFX009/FX082.mp3", [i](bool isSucceed){
                log("222: %d preload %s", i, isSucceed ? "succeed" : "failed");
                AudioEngine::preload("audio/SoundEffectsFX009/FX082.mp3", [i](bool isSucceed){
                    log("333: %d preload %s", i, isSucceed ? "succeed" : "failed");
                });
            });
        });
```

### PR DESCRIPTION
**Pull request by dumganhar**

### CODE REVIEW

File: tests/cpp-tests/Classes/NewAudioEngineTest/NewAudioEngineTest.cpp [hunk 1]
```diff
@@ -189,7 +190,7 @@ AudioEngineTestDemo::AudioEngineTestDemo()
 void AudioEngineTestDemo::onExit()
 {
     *_isDestroyed = true;
-    AudioEngine::stopAll();
+    AudioEngine::uncacheAll();
```
Comment (dumganhar) [inline tests/cpp-tests/Classes/NewAudioEngineTest/NewAudioEngineTest.cpp:193]: After this line was changed to `uncacheAll`, it will trigger a bug http://punchbox.info:3000/issues/26038.
It only crash on win32 platform. I will try to fix it.
