### PR TITLE
fixed #16490: [android, audio] AudioEngine::stop() triggers 'finished' callback

### LINKED ISSUE #16490: [android, audio] AudioEngine::stop() triggers 'finished' callback
Reported at http://forum.cocos.com/t/cocos2d-x-3-13-android-audioengine-stop/39432
- cocos2d-x version: 3.13
- devices test on: Android
- developing environments
  - NDK version: r10e

Steps to Reproduce:
1. NewAudioEngineTest -> ControlTest
2. Click play, then click stop button
3. finished callback will be triggered

### PR DESCRIPTION
**Pull request by dumganhar**

### CODE REVIEW

File: cocos/audio/android/AudioEngine-inl.cpp [hunk 1]
```diff
@@ -225,11 +225,15 @@ int AudioEngineImpl::play2d(const std::string &filePath ,bool loop ,float volume
...
-                ALOGV("Removing player id=%d", id);
+                ALOGV("Removing player id=%d, state:%d", id, (int)state);
+
                 auto iter = _callbackMap.find(id);
                 if (iter != _callbackMap.end())
                 {
-                    iter->second(id, *AudioEngine::_audioIDInfoMap[id].filePath);
+                    if (state == IAudioPlayer::State::OVER)
+                    {
+                        iter->second(id, *AudioEngine::_audioIDInfoMap[id].filePath);
```
Comment (dumganhar) [inline cocos/audio/android/AudioEngine-inl.cpp:235]: Only `OVER` status should trigger `finished` callback.
