### PR TITLE
Fix XmlHttpRequestTest parsing error of response header on iOS platform

### LINKED ISSUE #9788: XmlHttpRequest for Lua can't get the correct _statusText on the iOS and android platform

### PR DESCRIPTION
**Pull request by ghost**
fix #9788

### CODE REVIEW

File: cocos/network/HttpAsynConnection.m [hunk 1]
```diff
@@ -73,7 +74,10 @@ - (void) connection:(NSURLConnection *)connection
     responseHeader = [[httpResponse allHeaderFields] copy];
 
     responseCode = httpResponse.statusCode;
-    if (responseCode != 200)
+    statusString = [[NSHTTPURLResponse localizedStringForStatusCode:responseCode] copy];
+    if(responseCode == 200)
+        statusString = @"OK";
+    if (responseCode/100 != 2)
```
Comment (dabingnn) [inline cocos/network/HttpAsynConnection.m]: 1.Why using magic code `200`?
2. Is `if (responseCode/100 != 2)` different from `if(responseCode != 200)`?

Comment (ghost) [inline cocos/network/HttpAsynConnection.m]: That is because when responseCode is 200 the statusString of iOS is different with other platform.
