### PR TITLE
fix blur shader compliant on win8 universal.

### LINKED ISSUE #12505: Resources/Shaders/example_Blur.fsh is not OpenGL ES 2.0 compliant
The for loop in Resources/Shaders/example_Blur.fsh is not OpenGL ES 2.0 compliant and will not compile on some platforms that enforce the requirement that control flow be limited to forward branching and to loops where the maximum number of iterations can easily be determined at compile time. 

The use of the calculated value r from a uniform value means the maximum number of loop iterations cannot be known by the shader compiler. Angle for Windows 8.1 and 10 enforces this requirement. Other platforms may skip the for loop entirely without the compiler reporting an error.

The blur shader does the following:

uniform float blurRadius;
...
float r = blurRadius;
...
for(float x = -r; x < r; x += sampleStep) // error! compiler cannot unroll this loop 

The blur shader is not a correct GLSL shader.

See Appendix A section 4: Flow Control of the GLSL spec.

https://www.khronos.org/registry/gles/specs/2.0/GLSL_ES_Specification_1.0.17.pdf

### PR DESCRIPTION
**Pull request by fusijie**
To fix #12505

### CODE REVIEW

**Comment by fusijie** [comment]
@yangws please help to review.

**Comment by yangws** [comment]
@pandamicro 
review ok, all seem's good.

File: tests/cpp-tests/Classes/ShaderTest/ShaderTest.cpp [hunk 1]
```diff
@@ -401,17 +401,25 @@ bool SpriteBlur::initWithTexture(Texture2D* texture, const Rect& rect)
...
 {
-    GLchar * fragSource = (GLchar*) FileUtils::getInstance()->getStringFromFile(
-                                FileUtils::getInstance()->fullPathForFilename("Shaders/example_Blur.fsh")).c_str();
-    auto program = GLProgram::createWithByteArrays(ccPositionTextureColor_noMVP_vert, fragSource);
+	GLchar * fragSource = nullptr;
+#if (CC_TARGET_PLATFORM != CC_PLATFORM_WINRT)
+    fragSource = (GLchar*) String::createWithContentsOfFile(
+                                FileUtils::getInstance()->fullPathForFilename("Shaders/example_Blur.fsh").c_str())->getCString();  
+#else
+	fragSource = (GLchar*)String::createWithContentsOfFile(
```
Comment (pandamicro) [inline tests/cpp-tests/Classes/ShaderTest/ShaderTest.cpp]: Please use 4 spaces instead of tab, check all new lines please
