### PR TITLE
DrawNode override drawPoints function to set pointSize, fix draw points ...

### LINKED ISSUE #8844: DrawNode::drawPoints(), cannot set pointSize
```
void drawPoint(const Vec2& point, const float pointSize, const Color4F &color);

void drawPoints(const Vec2 *position, unsigned int numberOfPoints, const Color4F &color);
```

`drawPoints` has no `pointSize` argument, whereas `drawPoint` has it. How to set the size?

### PR DESCRIPTION
**Pull request by ghost**
...use last color bug and drawRect behavior bug

fix #8844 #9493 #8963

### CODE REVIEW

File: cocos/2d/CCDrawNode.cpp [hunk 1]
```diff
@@ -662,23 +665,7 @@ void DrawNode::drawDot(const Vec2 &pos, float radius, const Color4F &color)
...
-    V2F_C4B_T2F_Triangle *triangles = (V2F_C4B_T2F_Triangle *)(_buffer + _bufferCount);
-    V2F_C4B_T2F_Triangle triangle0 = {a, b, c};
-    V2F_C4B_T2F_Triangle triangle1 = {a, c, d};
-    triangles[0] = triangle0;
-    triangles[1] = triangle1;
-	
-    _bufferCount += vertex_count;
-
-    _dirty = true;
+    drawRect(lb, rt, color);
```
Comment (dabingnn) [inline cocos/2d/CCDrawNode.cpp]: If the rect is rotated, the effect would be wrong.

**Comment by minggo** [comment]
Please add corresponding test cases.
