### PR TITLE
Fix  #14428 CCRenderTexture does not work properly on some devices wh…

### LINKED ISSUE #14428: CCRenderTexture does not work properly on some devices which do not support "GL_OES_packed_depth_stencil".
Some android devices which do not support "GL_OES_packed_depth_stencil" will draw white box for CCClippingNode. To make it work CCRenderTexture should make two render buffers for stencil and depth.

### PR DESCRIPTION
**Pull request by kcisoul**
Fix  #14428 CCRenderTexture does not work properly on some devices which do not support "GL_OES_packed_depth_stencil".

### CODE REVIEW

**Comment by kongfamily0804** [comment]
Hi

File: cocos/2d/CCRenderTexture.cpp [hunk 1]
```diff
@@ -252,16 +259,49 @@ bool RenderTexture::initWithWidthAndHeight(int w, int h, Texture2D::PixelFormat
...
-            glGenRenderbuffers(1, &_depthRenderBufffer);
-            glBindRenderbuffer(GL_RENDERBUFFER, _depthRenderBufffer);
-            glRenderbufferStorage(GL_RENDERBUFFER, depthStencilFormat, (GLsizei)powW, (GLsizei)powH);
-            glFramebufferRenderbuffer(GL_FRAMEBUFFER, GL_DEPTH_ATTACHMENT, GL_RENDERBUFFER, _depthRenderBufffer);
-
-            // if depth format is the one with stencil part, bind same render buffer as stencil attachment
-            if (depthStencilFormat == GL_DEPTH24_STENCIL8)
+            
+            
+            const char* extString = (const char*)glGetString(GL_EXTENSIONS);
```
Comment (zhaijialong) [inline cocos/2d/CCRenderTexture.cpp]: This is no need to query the extension every time a RenderTexture created, you should put it in the `Configuration` class.

Comment (kcisoul) [inline cocos/2d/CCRenderTexture.cpp]: Thanks. I changed some code

File: cocos/2d/CCRenderTexture.cpp [hunk 2]
```diff
@@ -252,17 +259,62 @@ bool RenderTexture::initWithWidthAndHeight(int w, int h, Texture2D::PixelFormat
...
+                }
+            }
+            else
+            {
+
+                glGenRenderbuffers(1, &_depthRenderBufffer);
+                glGenRenderbuffers(1, &_stencilRenderBufffer);
+                glBindRenderbuffer(GL_RENDERBUFFER, _depthRenderBufffer);
+                
+                if(Configuration::getInstance()->supportsOESPackedDepthStencil())
```
Comment (zhaijialong) [inline cocos/2d/CCRenderTexture.cpp]: I think you wanted to use `supportsOESDepth24` here?

Comment (kcisoul) [inline cocos/2d/CCRenderTexture.cpp]: need to check whether an android device supports both supportsOESDepth24 and supportsOESPackedDepthStencil :)

Comment (zhaijialong) [inline cocos/2d/CCRenderTexture.cpp]: Yes, but you only checked `supportsOESPackedDepthStencil` now...

Comment (kcisoul) [inline cocos/2d/CCRenderTexture.cpp]: I did't notice that. thanks :)

**Comment by zilongshanren** [comment]
@zhaijialong  @kcisoul  
thanks, guys, sorry for the late reply.
