### PR TITLE
fixed #16849: Preload many audios may cause crash on devices those use Samsung Exynos CPU.

### LINKED ISSUE #16849: Crash when preload sounds with AudioEngine on Android
- cocos2d-x version: 3.13.1
- developing environments
   - NDK version: 22
- Android version 5.1.1

Hi @dumganhar  

When we preload sounds with AudioEngine on android we have a random crash. It only happens on a Samsung Galaxy S6 Edge.
We are preloading between 80 to 100 ogg, if we don't preload and play the sounds we don't have any crash but we have a lot of delay trying to play a sound, also the game freeze for some frames.

This is new for us since we updated to version 3.13.1 recently.

Thanks for the help!

### This is the crash:

V/AudioDecoder(30916): decodeToPcmCallback ...

V/AudioDecoder(30916): resample() 86400 output frames

V/AudioDecoder(30916): outFrames: 172800

V/AudioDecoder(30916): resample() complete

V/AudioDecoder(30916): reset() complete

V/AudioResampler(30916): resampler load 12 -> 6 MHz due to delta -6 MHz from quality 2

V/AudioDecoder(30916): decodeToPcmCallback ...

I/DEBUG   ( 2961): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***

I/DEBUG   ( 2961): Build fingerprint: 'samsung/zeroltexx/zerolte:5.1.1/LMY47X/G925FXXU3QPA7:user/release-keys'

I/DEBUG   ( 2961): Revision: '10'

I/DEBUG   ( 2961): ABI: 'arm'

I/DEBUG   ( 2961): pid: 30916, tid: 31214, name: GLThread 2674  >>> com.ironhidegames.kingdomrushx <<<

I/DEBUG   ( 2961): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x7bdef7bd

I/DEBUG   ( 2961):     r0 5294a529  r1 f4c00000  r2 4a5294a5  r3 00000109

I/DEBUG   ( 2961):     r4 ee812808  r5 ee811000  r6 d856d000  r7 f6fc2fc8

I/DEBUG   ( 2961):     r8 000000ff  r9 ee8127e8  sl ee849bd0  fp f6fc2fd8

I/DEBUG   ( 2961):     ip f6fb67cc  sp d3151d50  lr f6f95fcf  pc f6f9614a  cpsr 200f0030

I/DEBUG   ( 2961): 

I/DEBUG   ( 2961): backtrace:

I/DEBUG   ( 2961):     #00 pc 0004a14a  /system/lib/libc.so (ifree+665)

I/DEBUG   ( 2961):     #01 pc 00012d57  /system/lib/libc.so (free+10)

I/DEBUG   ( 2961):     #02 pc 000017d4  /system/lib/libExynosOMX_Core.so (Exynos_OMX_Component_Unregister+4)

I/DEBUG   ( 2961):     #03 pc 00001bd8  /system/lib/libExynosOMX_Core.so (Exynos_OMX_Deinit+44)

I/DEBUG   ( 2961):     #04 pc 00000e51  /system/lib/libstagefrighthw.so (android::ExynosOMXPlugin::~ExynosOMXPlugin()+24)

I/DEBUG   ( 2961):     #05 pc 00000e7d  /system/lib/libstagefrighthw.so (android::ExynosOMXPlugin::~ExynosOMXPlugin()+4)

I/DEBUG   ( 2961):     #06 pc 00014ea9  /system/lib/libstagefright_omx.so (android::OMXMaster::clearPlugins()+60)

I/DEBUG   ( 2961):     #07 pc 00014edb  /system/lib/libstagefright_omx.so (android::OMXMaster::~OMXMaster()+18)

I/DEBUG   ( 2961):     #08 pc 00014f2d  /system/lib/libstagefright_omx.so (android::OMXMaster::~OMXMaster()+4)

I/DEBUG   ( 2961):     #09 pc 00013627  /system/lib/libstagefright_omx.so (android::OMX::~OMX()+42)

I/DEBUG   ( 2961):     #10 pc 000136ad  /system/lib/libstagefright_omx.so (android::OMX::~OMX()+4)

I/DEBUG   ( 2961):     #11 pc 0000ede5  /system/lib/libutils.so (android::RefBase::decStrong(void const*) const+40)

I/DEBUG   ( 2961):     #12 pc 00072213  /system/lib/libstagefright.so (android::sp<android::IGraphicBufferProducer>::~sp()+18)

I/DEBUG   ( 2961):     #13 pc 000b3bc1  /system/lib/libstagefright.so (android::MuxOMX::~MuxOMX()+36)

I/DEBUG   ( 2961):     #14 pc 000b3c01  /system/lib/libstagefright.so (android::MuxOMX::~MuxOMX()+4)

I/DEBUG   ( 2961):     #15 pc 0000ede5  /system/lib/libutils.so (android::RefBase::decStrong(void const*) const+40)

I/DEBUG   ( 2961):     #16 pc 00072213  /system/lib/libstagefright.so (android::sp<android::IGraphicBufferProducer>::~sp()+18)

I/DEBUG   ( 2961):     #17 pc 000b9def  /system/lib/libstagefright.so (android::OMXCodec::~OMXCodec()+338)

I/DEBUG   ( 2961):     #18 pc 000b9e55  /system/lib/libstagefright.so (android::OMXCodec::~OMXCodec()+4)

I/DEBUG   ( 2961):     #19 pc 0000ede5  /system/lib/libutils.so (android::RefBase::decStrong(void const*) const+40)

I/DEBUG   ( 2961):     #20 pc 0000beab  /system/lib/libwilhelm.so

I/DEBUG   ( 2961):     #21 pc 0000c6fd  /system/lib/libwilhelm.so

I/DEBUG   ( 2961):     #22 pc 0000d2a7  /system/lib/libwilhelm.so

I/DEBUG   ( 2961):     #23 pc 0000d2b9  /system/lib/libwilhelm.so

I/DEBUG   ( 2961):     #24 pc 0000ede5  /system/lib/libutils.so (android::RefBase::decStrong(void const*) const+40)

I/DEBUG   ( 2961):     #25 pc 0000a0d1  /system/lib/libwilhelm.so

I/DEBUG   ( 2961):     #26 pc 000141cd  /system/lib/libwilhelm.so

I/DEBUG   ( 2961):     #27 pc 000192b3  /system/lib/libwilhelm.so

I/DEBUG   ( 2961):     #28 pc 009de3d3  /data/app/com.ironhidegames.kingdomrushx-1/lib/arm/libcocos2dcpp.so (cocos2d::experimental::AudioDecoder::decodeToPcm()+8146)

I/DEBUG   ( 2961):     #29 pc 009dbdb5  /data/app/com.ironhidegames.kingdomrushx-1/lib/arm/libcocos2dcpp.so (cocos2d::experimental::AudioDecoder::start()+52)

I/DEBUG   ( 2961):     #30 pc 0098dd9b  /data/app/com.ironhidegames.kingdomrushx-1/lib/arm/libcocos2dcpp.so

I/DEBUG   ( 2961):     #31 pc 009a3125  /data/app/com.ironhidegames.kingdomrushx-1/lib/arm/libcocos2dcpp.so

I/DEBUG   ( 2961):     #32 pc 009a02d9  /data/app/com.ironhidegames.kingdomrushx-1/lib/arm/libcocos2dcpp.so

I/DEBUG   ( 2961):     #33 pc 0076faeb  /data/app/com.ironhidegames.kingdomrushx-1/lib/arm/libcocos2dcpp.so (std::__ndk1::function<void (int)>::operator()(int) const+82)

I/DEBUG   ( 2961):     #34 pc 009d126b  /data/app/com.ironhidegames.kingdomrushx-1/lib/arm/libcocos2dcpp.so

I/DEBUG   ( 2961):     #35 pc 009db8b1  /data/app/com.ironhidegames.kingdomrushx-1/lib/arm/libcocos2dcpp.so

I/DEBUG   ( 2961):     #36 pc 009db821  /data/app/com.ironhidegames.kingdomrushx-1/lib/arm/libcocos2dcpp.so

I/DEBUG   ( 2961):     #37 pc 0076faeb  /data/app/com.ironhidegames.kingdomrushx-1/lib/arm/libcocos2dcpp.so (std::__ndk1::function<void (int)>::operator()(int) const+82)

I/DEBUG   ( 2961):     #38 pc 009d1e7b  /data/app/com.ironhidegames.kingdomrushx-1/lib/arm/libcocos2dcpp.so

I/DEBUG   ( 2961):     #39 pc 009d615d  /data/app/com.ironhidegames.kingdomrushx-1/lib/arm/libcocos2dcpp.so

I/DEBUG   ( 2961):     #40 pc 000174e7  /system/lib/libc.so (__pthread_start(void*)+30)

I/DEBUG   ( 2961):     #41 pc 00015503  /system/lib/libc.so (__start_thread+6)

### PR DESCRIPTION
**Pull request by dumganhar**

### CODE REVIEW

File: cocos/audio/android/AudioDecoder.cpp [hunk 1]
```diff
@@ -264,16 +270,19 @@ bool AudioDecoder::decodeToPcm()
...
-    result = (*_engineItf)->CreateAudioPlayer(_engineItf, &player, &decSource, &decDest,
-                                              NUM_EXPLICIT_INTERFACES_FOR_PLAYER, iidArray,
-                                              required);
-    SL_RETURN_VAL_IF_FAILED(result, false, "CreateAudioPlayer failed");
-
-    _playObj = player;
-    /* Realize the player in synchronous mode. */
-    result = (*player)->Realize(player, SL_BOOLEAN_FALSE);
-    SL_RETURN_VAL_IF_FAILED(result, false, "Realize failed");
+    {
```
Comment (formatCvt) [inline cocos/audio/android/AudioDecoder.cpp:273]: without this braces (line 273)

File: cocos/audio/android/AudioDecoder.cpp [hunk 2]
```diff
@@ -264,16 +270,19 @@ bool AudioDecoder::decodeToPcm()
...
+        result = (*_engineItf)->CreateAudioPlayer(_engineItf, &player, &decSource, &decDest,
+                                                  NUM_EXPLICIT_INTERFACES_FOR_PLAYER, iidArray,
+                                                  required);
+        SL_RETURN_VAL_IF_FAILED(result, false, "CreateAudioPlayer failed");
+
+        _playObj = player;
+        /* Realize the player in synchronous mode. */
+        result = (*player)->Realize(player, SL_BOOLEAN_FALSE);
+        SL_RETURN_VAL_IF_FAILED(result, false, "Realize failed");
+    }
```
Comment (formatCvt) [inline cocos/audio/android/AudioDecoder.cpp:285]: without this braces  (line 285)

File: cocos/audio/android/AudioDecoder.cpp [hunk 3]
```diff
@@ -468,8 +477,11 @@ bool AudioDecoder::decodeToPcm()
 
     ALOGV("Stopped decoding");
 
-    /* Destroy the UrlAudioPlayer object */
-    SL_DESTROY_OBJ(_playObj);
+    /* Destroy the AudioPlayer object */
+    {
```
Comment (formatCvt) [inline cocos/audio/android/AudioDecoder.cpp:481]: without this braces  (line 481)

File: cocos/audio/android/AudioDecoder.cpp [hunk 4]
```diff
@@ -468,8 +477,11 @@ bool AudioDecoder::decodeToPcm()
...
+        std::lock_guard<std::mutex> lk(__SLPlayerMutex);
```
Comment (formatCvt) [inline cocos/audio/android/AudioDecoder.cpp:482]: this lock  (line 482)

File: cocos/audio/android/AudioDecoder.cpp [hunk 5]
```diff
@@ -468,8 +477,11 @@ bool AudioDecoder::decodeToPcm()
...
+        SL_DESTROY_OBJ(_playObj);
+    }
```
Comment (formatCvt) [inline cocos/audio/android/AudioDecoder.cpp:484]: and without this braces (line 484) working fine for me (Samsung Galaxy Grand).

**Review by formatCvt — COMMENTED** [review]
in other words - lock from creation to destroying player  working fine for me (Samsung Galaxy Grand).

File: cocos/audio/android/AudioDecoder.cpp (hunk 5 above)
Comment (dumganhar) [reply cocos/audio/android/AudioDecoder.cpp:484]: It's better to add the braces since `std::lock_guard` needs it to unlock mutex right after SL_DESTROY_OBJ. Otherwise, the `unlock` operation will be delayed to the function return.

Comment (dumganhar) [reply cocos/audio/android/AudioDecoder.cpp:484]: It's odd, in fact, with or without this brace will make the same result.

Comment (formatCvt) [reply cocos/audio/android/AudioDecoder.cpp:484]: yes, with my changes i mean delay unlock operation to the function return.

File: cocos/audio/android/AudioDecoder.cpp (hunk 2 above)
Comment (dumganhar) [reply cocos/audio/android/AudioDecoder.cpp:285]: If without `}` after `->Realize`, multi-thread decoding will be broken. Although, it does use multi-threads, all tasks in thread pool will wait previous decoding task to finish, then start. So removing this brace will make no sense.

File: cocos/audio/android/AudioDecoder.cpp (hunk 5 above)
Comment (dumganhar) [reply cocos/audio/android/AudioDecoder.cpp:484]: Could you remove `}` after SL_DESTROY_OBJ, but keep it after `->Realize`, and test it again?

Comment (formatCvt) [reply cocos/audio/android/AudioDecoder.cpp:484]: there are 3 diff's. Two doesn’t work, and 1 work.
[doesnt-work1-pull17049.diff.txt](https://github.com/cocos2d/cocos2d-x/files/666633/doesnt-work1-pull17049.diff.txt)
[doesnt-work2-pull17049.diff.txt](https://github.com/cocos2d/cocos2d-x/files/666637/doesnt-work2-pull17049.diff.txt)
[work-pull17049.diff.txt](https://github.com/cocos2d/cocos2d-x/files/666639/work-pull17049.diff.txt)

Comment (formatCvt) [reply cocos/audio/android/AudioDecoder.cpp:484]: more experiments
[work2-pull17049.txt](https://github.com/cocos2d/cocos2d-x/files/666786/work2-pull17049.txt)
[doesnt-work3-pull17049.txt](https://github.com/cocos2d/cocos2d-x/files/666789/doesnt-work3-pull17049.txt)
